Repository sgdevcamp2023/recycle, pull requests merged in 2024-01, with the labels that each got.

#15 [BE/#14] fix: spotless가 각 서브 프로젝트에 적용되지 않는 문제
  be/build.gradle
  be/flyway/src/main/java/com/zzaug/flyway/config/EntityFlywayConfig.java
  be/member/src/main/java/com/zzaug/member/domain/usecase/member/MemberConverter.java
  be/member/src/main/java/com/zzaug/member/domain/usecase/member/MemberUseCase.java
  be/member/src/main/java/com/zzaug/member/web/controller/v1/member/MemberController.java
  be/notification/src/main/java/com/zzaug/notification/domain/usecase/notification/NotificationConverter.java
  be/notification/src/main/java/com/zzaug/notification/domain/usecase/notification/NotificationUseCase.java
  be/notification/src/main/java/com/zzaug/notification/web/controller/v1/notification/NotificationController.java
  be/review/src/main/java/com/zzaug/review/domain/usecase/review/ReviewConverter.java
  be/review/src/main/java/com/zzaug/review/domain/usecase/review/ReviewUseCase.java
  be/review/src/main/java/com/zzaug/review/web/controller/v1/notification/ReviewController.java
  be/security/src/main/java/com/zzaug/security/config/SecurityConfig.java
  be/security/src/main/java/com/zzaug/security/filter/token/TokenAuthenticationFilter.java
Labels: 백엔드

#16 BE 팀이 필요한 .github에 포함될 파일입니다.
  .github/PULL_REQUEST_TEMPLATE/be_pr_template.md
  .github/workflow/lint.yml
Labels: 백엔드, 공통

#73 [FE/#53] chore: storybook 적용
  fe/.eslintrc.cjs
  fe/.storybook/main.ts
  fe/.storybook/preview.ts
  fe/package-lock.json
  fe/package.json
  fe/src/stories/Button.stories.ts
  fe/src/stories/Button.tsx
  fe/src/stories/Configure.mdx
  fe/src/stories/Header.stories.ts
  fe/src/stories/Header.tsx
  fe/src/stories/Page.stories.ts
  fe/src/stories/Page.tsx
  fe/src/stories/assets/accessibility.png
  fe/src/stories/assets/accessibility.svg
  fe/src/stories/assets/addon-library.png
  fe/src/stories/assets/assets.png
  fe/src/stories/assets/avif-test-image.avif
  fe/src/stories/assets/context.png
  fe/src/stories/assets/discord.svg
  fe/src/stories/assets/docs.png
  fe/src/stories/assets/figma-plugin.png
  fe/src/stories/assets/github.svg
  fe/src/stories/assets/share.png
  fe/src/stories/assets/styling.png
  fe/src/stories/assets/testing.png
  fe/src/stories/assets/theming.png
  fe/src/stories/assets/tutorials.svg
  fe/src/stories/assets/youtube.svg
  fe/src/stories/button.css
  fe/src/stories/header.css
  fe/src/stories/page.css
Labels: 프런트

#75 [FE/#71] feat: 디렉토리 구조 적용
  fe/src/api/axios.ts
  fe/src/components/atom/temp.tsx
  fe/src/components/block/temp.tsx
  fe/src/components/layout/grid.tsx
  fe/src/hooks/test.ts
  fe/src/page/main.tsx
  fe/src/routes/router.ts
  fe/src/store/store.ts
  fe/src/styles/styles.ts
Labels: 프런트

#76 [FE/#74] chore: 절대 경로 적용 완료
  fe/tsconfig.json
  fe/vite.config.ts
Labels: 프런트

#83 [FE/#65] 기본페이지, 라우팅 부분 업데이트
  fe/src/App.tsx
  fe/src/main.tsx
  fe/src/page/Index.tsx
  fe/src/page/Login.tsx
  fe/src/page/NotFound.tsx
  fe/src/page/SignUp.tsx
  fe/src/page/TestPage.tsx
  fe/src/page/main.tsx
  fe/src/routes/router.ts
  fe/src/routes/router.tsx
Labels: 프런트

#79 [Be/#54] Docs: 멤버 서버 Mock API 구현
  be/member-api/src/main/java/com/zzaug/member/domain/dto/member/CheckDuplicationUseCaseRequest.java
  be/member-api/src/main/java/com/zzaug/member/domain/dto/member/CheckDuplicationUseCaseResponse.java
  be/member-api/src/main/java/com/zzaug/member/domain/dto/member/CheckEmailAuthUseCaseRequest.java
  be/member-api/src/main/java/com/zzaug/member/domain/dto/member/CheckEmailAuthUseCaseResponse.java
  be/member-api/src/main/java/com/zzaug/member/domain/dto/member/DeleteMemberUseCaseRequest.java
  be/member-api/src/main/java/com/zzaug/member/domain/dto/member/EmailAuthUseCaseRequest.java
  be/member-api/src/main/java/com/zzaug/member/domain/dto/member/EmailAuthUseCaseResponse.java
  be/member-api/src/main/java/com/zzaug/member/domain/dto/member/GetMemberUseCaseRequest.java
  be/member-api/src/main/java/com/zzaug/member/domain/dto/member/GetMemberUseCaseResponse.java
  be/member-api/src/main/java/com/zzaug/member/domain/dto/member/LogOutUseCaseRequest.java
  be/member-api/src/main/java/com/zzaug/member/domain/dto/member/LoginUseCaseRequest.java
  be/member-api/src/main/java/com/zzaug/member/domain/dto/member/MemberAuthToken.java
  be/member-api/src/main/java/com/zzaug/member/domain/dto/member/PostMemberUseCaseRequest.java
  be/member-api/src/main/java/com/zzaug/member/domain/dto/member/SearchMemberUseCaseRequest.java
  be/member-api/src/main/java/com/zzaug/member/domain/dto/member/SearchMemberUseCaseResponse.java
  be/member-api/src/main/java/com/zzaug/member/domain/dto/member/UpdateMemberUseCaseRequest.java
  be/member-api/src/main/java/com/zzaug/member/support/ApiResponse.java
  be/member-api/src/main/java/com/zzaug/member/support/ApiResponseGenerator.java
  be/member-api/src/main/java/com/zzaug/member/web/controller/v1/member/MemberCheckController.java
  be/member-api/src/main/java/com/zzaug/member/web/controller/v1/member/MemberController.java
  be/member-api/src/main/java/com/zzaug/member/web/dto/member/CheckEmailAuthRequest.java
  be/member-api/src/main/java/com/zzaug/member/web/dto/member/LoginRequest.java
  be/member-api/src/main/java/com/zzaug/member/web/dto/member/MemberSaveRequest.java
  be/member-api/src/main/java/com/zzaug/member/web/dto/member/MemberUpdateRequest.java
  be/member-api/src/test/java/com/zzaug/member/web/controller/v1/MemberControllerTest.java
  be/member-api/src/test/java/com/zzaug/member/web/controller/v1/description/Description.java
  be/member-api/src/test/java/com/zzaug/member/web/controller/v1/member/MemberCheckControllerTest.java
  be/member-api/src/test/java/com/zzaug/member/web/controller/v1/member/MemberControllerTest.java
Labels: 백엔드

#80 [Be/#78] Refactor: 시큐리티 모듈 관련 설정 추가 및 수정
  be/docs/member/ARCHITECTURE.md
  be/docs/member/EVENT.md
  be/scripts/recycle-develop-keystore
  be/security/src/main/java/com/zzaug/security/authentication/token/TokenUserDetails.java
  be/security/src/main/java/com/zzaug/security/authentication/token/TokenUserDetailsService.java
  be/security/src/main/java/com/zzaug/security/config/CorsConfigurationSourceProperties.java
  be/security/src/main/java/com/zzaug/security/config/WebSecurityConfig.java
  be/security/src/main/java/com/zzaug/security/token/TokenGenerator.java
  be/security/src/main/resources/application-security-dev.yml
  be/security/src/main/resources/application-security-local.yml
  be/security/src/main/resources/application-security-prod.yml
  be/security/src/main/resources/application-security.yml
  be/security/src/main/resources/application-server-ssl.yml
Labels: 백엔드

#85 [Be/#54] Docs: 멤버 서버 Mock 문서 입니다.
  be/docs/member/API.md
  be/docs/member/ARCHITECTURE.md
  be/docs/member/DEVELOP.md
  be/docs/member/EVENT.md
Labels: 백엔드

#87 [Be/#49] Docs: 리뷰 서버 Mock 문서입니다.
  be/docs/COMMENT/API.md
  be/docs/COMMENT/DEVELOP.md
  be/docs/QUESTION/API.md
  be/docs/QUESTION/ARCHITECTURE.md
  be/docs/QUESTION/DEVELOP.md
  be/docs/QUESTION/EVENT.md
  be/docs/REVIEW/API.md
  be/docs/REVIEW/DEVELOP.md
  be/docs/REVIEW/EVENT.md
  be/review-api/src/main/java/com/zzaug/review/web/controller/v1/review/ReviewController.java
Labels: 백엔드

#102 [Fe/#101] 로그인 폼 구현
  fe/src/assets/icons/minus.png
  fe/src/assets/icons/pencil.svg
  fe/src/assets/icons/plus.png
  fe/src/assets/logos/ZzaugLogo.png
  fe/src/components/atom/Button/BelowCommentButton.tsx
  fe/src/components/atom/Button/CommonButton.tsx
  fe/src/components/atom/Button/DoubleCheckButton.tsx
  fe/src/components/atom/Button/ModifyButton.tsx
  fe/src/components/atom/Button/PaginationButton.tsx
  fe/src/components/atom/Button/ReplyOfCommentButton.tsx
  fe/src/components/atom/Button/ReturnButton.tsx
  fe/src/components/atom/Button/ReviewButton.tsx
  fe/src/components/atom/Button/TemporaryStorageButton.tsx
  fe/src/components/atom/Button/ToggleButton.tsx
  fe/src/components/atom/Comment/LineCommentView.tsx
  fe/src/components/atom/Comment/LineCommentWrite.tsx
  fe/src/components/atom/Input/CommonInput.tsx
  fe/src/components/atom/Input/DefaultInput.tsx
  fe/src/components/atom/Input/ReplyOfCommentInput.tsx
  fe/src/components/atom/Text.tsx
  fe/src/components/block/modal/BackgroundModal.tsx
  fe/src/components/block/modal/LoginModal.tsx
  fe/src/components/block/modal/SignInModal.tsx
  fe/src/components/block/sideBar/SideBar.tsx
  fe/src/main.tsx
  fe/src/page/Login.tsx
  fe/src/page/TestPage.tsx
  fe/src/page/TestPageTwo.tsx
  fe/src/routes/router.tsx
  fe/src/store/useModalStore.ts
  fe/src/styles/flexCenter.ts
  fe/src/styles/theme.ts
  fe/vite.config.ts
Labels: 프런트

#110 [Fe/#103] 회원가입 폼 구현
  fe/src/components/atom/Input/CommonInput.tsx
  fe/src/components/block/modal/SignInModal.tsx
  fe/src/page/SignUp.tsx
Labels: 프런트

#109 [Fe/#65] common components
  fe/package-lock.json
  fe/package.json
  fe/src/assets/icons/ZZAUG_Logo.png
  fe/src/assets/icons/logout.svg
  fe/src/assets/icons/question.svg
  fe/src/assets/icons/request.svg
  fe/src/assets/icons/review.svg
  fe/src/assets/icons/setting.svg
  fe/src/components/block/sideBar/SideBar.tsx
  fe/src/components/layout/grid.tsx
  fe/src/custom.d.ts
  fe/src/page/TestPageTwo.tsx
  fe/src/styles/theme.ts
  fe/src/svg.d.ts
  fe/tsconfig.json
  fe/vite.config.ts
Labels: 프런트

#115 [Fe/#114] SaveModal 구현
  fe/src/components/atom/Button/ReturnButton.tsx
  fe/src/components/atom/Button/SaveReviewButton.tsx
  fe/src/components/atom/Button/TemporaryStorageButton.tsx
  fe/src/components/block/modal/SaveModal.tsx
  fe/src/page/TestPageThree.tsx
  fe/src/styles/theme.ts
Labels: 프런트

#117 [Fe/#106] layout grid template
  fe/src/App.css
  fe/src/components/block/sideBar/SideBar.tsx
  fe/src/components/layout/GridTemplate.tsx
  fe/src/index.css
  fe/src/page/TestPageTwo.tsx
  fe/src/routes/router.tsx
  fe/src/store/useTabStore.ts
  fe/src/styles/theme.ts
Labels: 프런트

#120 [Fe/#119] SharingModal 구현
  fe/src/assets/icons/linkIcon.png
  fe/src/assets/icons/searchIcon.png
  fe/src/components/atom/Button/InviteButton.tsx
  fe/src/components/block/modal/SharingModal.tsx
  fe/src/page/TestPageThree.tsx
Labels: 프런트

#124 [Fe/#123] LockModal 구현
  fe/src/assets/icons/Lock.png
  fe/src/components/block/modal/LockModal.tsx
  fe/src/components/block/modal/SaveModal.tsx
  fe/src/components/block/modal/SharingModal.tsx
  fe/src/page/TestPageThree.tsx
Labels: 프런트

#126 [Fe/#121] card components
  fe/src/components/atom/card/DefaultCard.tsx
  fe/src/components/atom/card/ReviewCard.tsx
  fe/src/components/atom/card/ReviewList.tsx
  fe/src/components/block/sideBar/SideBar.tsx
  fe/src/page/TestPageTwo.tsx
  fe/src/styles/theme.ts
Labels: 프런트

#127 [Fe/#125] RegisterEmailModal 구현
  fe/src/components/atom/Button/RegisterButton.tsx
  fe/src/components/block/modal/RegisterEmailModal.tsx
  fe/src/page/TestPageThree.tsx
Labels: 프런트

#128 [Fe/#122] tab components
  fe/src/components/block/navbar/ContentTab.tsx
  fe/src/components/block/navbar/DefaultTab.tsx
  fe/src/page/TestPageTwo.tsx
  fe/src/store/useTabStore.ts
  fe/src/styles/theme.ts
Labels: 프런트

#97 [Be/#27] Feat: 어플리케이션 실행 스크립트 추가
  be/scripts/restart_all
  be/scripts/run_all
  be/scripts/stop_all
Labels: 백엔드

#138 [Fe/#136] page router
  fe/src/components/block/Content/Question.tsx
  fe/src/components/block/Content/Request.tsx
  fe/src/components/block/Content/Review.tsx
  fe/src/components/block/Content/Setting.tsx
  fe/src/components/block/sideBar/SideBar.tsx
  fe/src/components/layout/GridTemplate.tsx
  fe/src/page/Common.tsx
  fe/src/page/Index.tsx
  fe/src/routes/router.tsx
  fe/src/store/useTabStore.ts
Labels: 프런트

#142 [Fe/#132] reviewtogitmodal 구현
  fe/src/assets/icons/github-mark.png
  fe/src/components/atom/Button/ExperienceButton.tsx
  fe/src/components/atom/Button/LinkToGitButton.tsx
  fe/src/components/block/modal/ReviewToGitModal.tsx
  fe/src/page/TestPageThree.tsx
Labels: 프런트

#143 [Fe/#132] sendemailmodal 구현
  fe/src/assets/icons/PhoneIcon.png
  fe/src/components/atom/Button/EmailEnrollButton.tsx
  fe/src/components/block/modal/SendEmailModal.tsx
  fe/src/page/TestPageThree.tsx
Labels: 프런트

#145 [Fe/144] 하단 댓글, 대댓글 modal 구현
  fe/src/components/atom/Button/BelowCommentButton.tsx
  fe/src/components/atom/Button/ReplyOfCommentButton.tsx
  fe/src/components/block/modal/BelowCommentModal.tsx
  fe/src/components/block/modal/BelowCommentReplyModal.tsx
  fe/src/page/TestPageThree.tsx
Labels: 프런트

#147 [Fe/#135] put page content
  fe/src/components/atom/card/DefaultCard.tsx
  fe/src/components/atom/card/ReviewCard.tsx
  fe/src/components/block/Content/Question.tsx
  fe/src/components/block/Content/Request.tsx
  fe/src/components/block/Content/Review.tsx
  fe/src/components/block/Content/Setting.tsx
  fe/src/components/block/Search/DefaultInput.tsx
  fe/src/components/block/Search/SearchInput.tsx
  fe/src/components/block/navbar/ContentTab.tsx
  fe/src/components/block/navbar/DefaultTab.tsx
  fe/src/components/layout/GridTemplate.tsx
  fe/src/page/Common.tsx
  fe/src/page/TestPageTwo.tsx
  fe/src/store/useTabStore.ts
Labels: 프런트

#96 [Be/#92] Feat: web module 분리
  be/dependencies/web-dependencies.gradle
  be/settings.gradle
  be/web/build.gradle
  be/web/src/main/java/com/zzaug/web/config/WebConfig.java
  be/web/src/main/java/com/zzaug/web/config/WebModuleConfig.java
  be/web/src/main/java/com/zzaug/web/exception/ExternalIntegrationException.java
  be/web/src/main/java/com/zzaug/web/exception/JsonParsingException.java
  be/web/src/main/java/com/zzaug/web/handler/ApiControllerExceptionHandler.java
  be/web/src/main/java/com/zzaug/web/handler/ExceptionMessage.java
  be/web/src/main/java/com/zzaug/web/handler/LoggingHandler.java
  be/web/src/main/java/com/zzaug/web/support/ApiResponse.java
  be/web/src/main/java/com/zzaug/web/support/ApiResponseGenerator.java
  be/web/src/main/java/com/zzaug/web/support/CookieGenerator.java
  be/web/src/main/java/com/zzaug/web/support/CookieSameSite.java
  be/web/src/main/java/com/zzaug/web/support/FailureBodyResolver.java
  be/web/src/main/java/com/zzaug/web/support/MessageCode.java
  be/web/src/main/java/com/zzaug/web/support/MessageSourceAccessor.java
  be/web/src/main/java/com/zzaug/web/support/Page.java
  be/web/src/main/resources/application-cookie-dev.yml
  be/web/src/main/resources/application-cookie-local.yml
  be/web/src/main/resources/application-cookie-prod.yml
  be/web/src/main/resources/application-cookie.yml
Labels: 백엔드

#149 [Be/#55] Docs: 알림 서버 문서 입니다
  be/docs/notification/API.md
  be/docs/notification/ARCHITECTURE.md
  be/docs/notification/DEVELOP.md
  be/docs/notification/EVENT.md
Labels: 백엔드

#148 [Be/#59] Feat: setting env
  be/rabbitmq/build.gradle
  be/rabbitmq/src/main/java/com/zzaug/rabbitmq/config/ZRMQConnectionConfig.java
  be/rabbitmq/src/main/java/com/zzaug/rabbitmq/config/ZRMQListenerConfig.java
  be/rabbitmq/src/main/java/com/zzaug/rabbitmq/config/ZRMQProperties.java
  be/rabbitmq/src/main/java/com/zzaug/rabbitmq/config/ZRabbiMQConfig.java
  be/rabbitmq/src/main/java/com/zzaug/rabbitmq/config/queue/DeadLetterQConfig.java
  be/rabbitmq/src/main/java/com/zzaug/rabbitmq/config/queue/MemberQConfig.java
  be/rabbitmq/src/main/java/com/zzaug/rabbitmq/config/queue/ReviewQConfig.java
  be/rabbitmq/src/main/java/com/zzaug/rabbitmq/listener/ZRMQExceptionHandler.java
  be/rabbitmq/src/main/java/com/zzaug/rabbitmq/listener/dead/DeadLetterListener.java
  be/rabbitmq/src/main/java/com/zzaug/rabbitmq/listener/dead/DeadLetterListenerConfig.java
  be/rabbitmq/src/main/java/com/zzaug/rabbitmq/listener/dead/DeadLetterMapper.java
  be/rabbitmq/src/main/java/com/zzaug/rabbitmq/listener/dead/DeadLetterMessage.java
  be/rabbitmq/src/main/resources/application-rabbit-dev.yml
  be/rabbitmq/src/main/resources/application-rabbit-local.yml
  be/rabbitmq/src/main/resources/application-rabbit-prod.yml
  be/rabbitmq/src/main/resources/application-rabbit.yml
  be/resources/recycle-develop-environment/docker-compose.yml
  be/resources/recycle-develop-environment/elasticsearch/config/elasticsearch.yml
  be/resources/recycle-develop-environment/kibana/config/kibana.yml
  be/resources/recycle-develop-environment/logstash/config/logstash.yml
  be/resources/recycle-develop-environment/logstash/pipeline/logstash.conf
  be/settings.gradle
Labels: 백엔드

#159 리뷰 관련 문서가 반영되지 않아 다시 PR 합니다.
  be/docs/COMMENT/API.md
  be/docs/COMMENT/DEVELOP.md
  be/docs/QUESTION/API.md
  be/docs/QUESTION/ARCHITECTURE.md
  be/docs/QUESTION/DEVELOP.md
  be/docs/QUESTION/EVENT.md
  be/docs/REVIEW/API.md
  be/docs/REVIEW/DEVELOP.md
  be/docs/REVIEW/EVENT.md
  be/review-api/src/main/java/com/zzaug/review/web/controller/v1/review/ReviewController.java
Labels: 백엔드

#174 [Fe/#153] create question
  fe/package-lock.json
  fe/package.json
  fe/src/components/atom/Input/DefaultInput.tsx
  fe/src/components/atom/card/DefaultCard.tsx
  fe/src/components/atom/card/ReviewCard.tsx
  fe/src/components/block/Content/CreateQuestion.tsx
  fe/src/components/block/Content/CreateReview.tsx
  fe/src/components/block/Content/Question.tsx
  fe/src/components/block/Content/Request.tsx
  fe/src/components/block/Content/Review.tsx
  fe/src/components/block/Editor/BlockNote.tsx
  fe/src/components/block/Search/DefaultInput.tsx
  fe/src/components/block/Search/SearchInput.tsx
  fe/src/components/block/navbar/ContentTab.tsx
  fe/src/components/block/sideBar/SideBar.tsx
  fe/src/page/BlackNoteTest.tsx
  fe/src/page/Common.tsx
  fe/src/routes/router.tsx
Labels: 프런트

#173 린트가 맞지 않은 rabbitmq 모듈의 파일이 있어 PR 합니다.
  be/rabbitmq/src/main/java/com/zzaug/rabbitmq/listener/dead/DeadLetterListener.java
  be/rabbitmq/src/main/java/com/zzaug/rabbitmq/listener/dead/DeadLetterMapper.java
Labels: 티켓, 백엔드

#175 [Fe/151] Button Components Refactoring
  fe/src/components/atom/Button/BelowCommentButton.tsx
  fe/src/components/atom/Button/CommonButton.tsx
  fe/src/components/atom/Button/DefaultButton.tsx
  fe/src/components/atom/Button/DoubleCheckButton.tsx
  fe/src/components/atom/Button/EmailEnrollButton.tsx
  fe/src/components/atom/Button/ExperienceButton.tsx
  fe/src/components/atom/Button/GreyButton.tsx
  fe/src/components/atom/Button/InviteButton.tsx
  fe/src/components/atom/Button/LinkToGitButton.tsx
  fe/src/components/atom/Button/ModifyButton.tsx
  fe/src/components/atom/Button/RegisterButton.tsx
  fe/src/components/atom/Button/ReturnButton.tsx
  fe/src/components/atom/Button/ReverseButton.tsx
  fe/src/components/atom/Button/ReviewButton.tsx
  fe/src/components/atom/Button/SaveReviewButton.tsx
  fe/src/components/atom/Button/TemporaryStorageButton.tsx
  fe/src/components/atom/Comment/LineCommentView.tsx
  fe/src/components/block/modal/AskLoginModal.tsx
  fe/src/components/block/modal/BelowCommentReplyModal.tsx
  fe/src/components/block/modal/LoginModal.tsx
  fe/src/components/block/modal/RegisterEmailModal.tsx
  fe/src/components/block/modal/ReviewToGitModal.tsx
  fe/src/components/block/modal/SaveModal.tsx
  fe/src/components/block/modal/SendEmailModal.tsx
  fe/src/components/block/modal/SharingModal.tsx
  fe/src/components/block/modal/SignInModal.tsx
  fe/src/page/TestPageThree.tsx
  fe/src/styles/theme.ts
Labels: 프런트

#180 [Fe/177] input Components refactoring
  fe/src/components/atom/Comment/BelowCommentWrite.tsx
  fe/src/components/atom/Comment/LineCommentView.tsx
  fe/src/components/atom/Input/CommonInput.tsx
  fe/src/components/atom/Input/CustomInput.tsx
  fe/src/components/atom/Input/DefaultInput.tsx
  fe/src/components/atom/Input/ReplyOfCommentInput.tsx
  fe/src/components/block/modal/LoginModal.tsx
  fe/src/components/block/modal/RegisterEmailModal.tsx
  fe/src/components/block/modal/SignInModal.tsx
  fe/src/page/TestPage.tsx
  fe/src/page/TestPageThree.tsx
  fe/src/styles/theme.ts
Labels: 프런트

#182 [FE/181] Button Components 대체 리팩터링
  fe/src/components/atom/Button/DefaultButton.tsx
  fe/src/components/atom/Button/GreyButton.tsx
  fe/src/components/block/navbar/ContentTab.tsx
  fe/src/components/block/navbar/DefaultTab.tsx
Labels: 프런트

#188 [feat/#186] feat: ErrorModal 추가
  fe/.prettierignore
  fe/index.html
  fe/src/components/atom/Button/DefaultButton.tsx
  fe/src/components/block/modal/ErrorModal.tsx
  fe/src/page/NotFound.tsx
  fe/src/routes/router.tsx
  fe/tsconfig.json
Labels: 프런트

#192 [fe/#154] api 명세서 기반 axois api 작성 완료
  fe/src/api/axios.ts
  fe/src/api/commentApi.ts
  fe/src/api/memberApi.ts
  fe/src/api/notificationApi.ts
  fe/src/api/questionApi.ts
  fe/src/api/reviewApi.ts
Labels: 프런트

#196 [Fe/146] MainPage 구현
  fe/src/assets/icons/Pencil.png
  fe/src/components/atom/Button/ReverseButton.tsx
  fe/src/page/Main.tsx
  fe/src/page/TestPageThree.tsx
  fe/src/routes/router.tsx
  fe/src/styles/theme.ts
Labels: 프런트

#207 feat: 버튼별 라우터 적용
  fe/src/components/block/modal/AskLoginModal.tsx
  fe/src/components/block/modal/LoginModal.tsx
  fe/src/components/block/modal/SendEmailModal.tsx
  fe/src/hooks/common/useMovePage.ts
  fe/src/page/Main.tsx
  fe/src/page/RegisterEmail.tsx
  fe/src/page/TestPageThree.tsx
  fe/src/routes/router.tsx
  fe/vite.config.ts
  fe/vite.config.ts.timestamp-1706507854540-5f6efe600778.mjs
Labels: 프런트

#210 [Fe/209] 깃허브, 이메일 계정 연동 AccountLinking 페이지 구현
  fe/src/components/block/modal/ReviewToGitModal.tsx
  fe/src/components/block/modal/SendEmailModal.tsx
  fe/src/page/AccountLinking.tsx
  fe/src/routes/router.tsx
Labels: 프런트, TODO

#211 [Fe/#189] react query hook
  fe/package-lock.json
  fe/package.json
  fe/src/api/axios.ts
  fe/src/api/commentApi.ts
  fe/src/api/memberApi.ts
  fe/src/api/notificationApi.ts
  fe/src/api/questionApi.ts
  fe/src/api/reviewApi.ts
  fe/src/components/atom/Button/DefaultButton.tsx
  fe/src/components/block/Search/DefaultInput.tsx
  fe/src/hooks/query/commnent/useCreateBelowComments.ts
  fe/src/hooks/query/commnent/useDeleteBelowComments.ts
  fe/src/hooks/query/commnent/useGetBelowComments.ts
  fe/src/hooks/query/commnent/useUpdateBelowComments.ts
  fe/src/hooks/query/member/useCheckEmailApprove.ts
  fe/src/hooks/query/member/useCheckId.ts
  fe/src/hooks/query/member/useCheckIdDuplicate.ts
  fe/src/hooks/query/member/useGetMemberInfo.ts
  fe/src/hooks/query/member/useLogin.ts
  fe/src/hooks/query/member/useLogout.ts
  fe/src/hooks/query/member/useRefreshToken.ts
  fe/src/hooks/query/member/useRequestEmailApprove.ts
  fe/src/hooks/query/member/useSignUp.ts
  fe/src/hooks/query/member/useUpdateMemberInfo.ts
  fe/src/hooks/query/notification/useRequestReview.ts
  fe/src/hooks/query/question/useCreateQuestion.ts
  fe/src/hooks/query/question/useDeleteQuestion.ts
  fe/src/hooks/query/question/useGetQuestion.ts
  fe/src/hooks/query/question/useGetQuestionReviewer.ts
  fe/src/hooks/query/question/useGetQuestions.ts
  fe/src/hooks/query/question/useGetReviewOnQuestionDraft.ts
  fe/src/hooks/query/question/useGetReviewRequests.ts
  fe/src/hooks/query/question/useGetReviews.ts
  fe/src/hooks/query/question/useGetReviewsOnQuestion.ts
  fe/src/hooks/query/question/useSaveQuestionDraft.ts
  fe/src/hooks/query/question/useSearchQuestions.ts
  fe/src/hooks/test.ts
  fe/src/main.tsx
  fe/src/page/APITestPage.tsx
  fe/src/routes/router.tsx
Labels: 프런트

#215 [Fe/#214] loginpage 유효성 검사 구현
  fe/src/components/atom/Input/CustomInput.tsx
  fe/src/components/block/modal/LoginModal.tsx
Labels: 프런트

#217 [Fe/#216] signuppage 유효성 검사 구현
  fe/src/components/block/modal/SignInModal.tsx
Labels: 프런트

#219 [Fe/#216] registerEmailPage 유효성 검사 구현
  fe/src/components/block/modal/RegisterEmailModal.tsx
Labels: 프런트

#235 [Fe/#228] member api apply
  fe/package-lock.json
  fe/package.json
  fe/src/api/axios.ts
  fe/src/api/memberApi.ts
  fe/src/components/atom/Button/DefaultButton.tsx
  fe/src/components/atom/Button/GreyButton.tsx
  fe/src/components/atom/Button/ReverseButton.tsx
  fe/src/components/atom/Button/TabButton.tsx
  fe/src/components/atom/Comment/BelowCommentWrite.tsx
  fe/src/components/atom/Comment/LineCommentView.tsx
  fe/src/components/atom/Input/CustomInput.tsx
  fe/src/components/atom/Text.tsx
  fe/src/components/block/Content/CreateQuestion.tsx
  fe/src/components/block/Content/Question.tsx
  fe/src/components/block/Content/Request.tsx
  fe/src/components/block/Content/Review.tsx
  fe/src/components/block/Content/Setting.tsx
  fe/src/components/block/Editor/BlockNote.tsx
  fe/src/components/block/Search/DefaultInput.tsx
  fe/src/components/block/modal/LoginModal.tsx
  fe/src/components/block/modal/RegisterEmailModal.tsx
  fe/src/components/block/modal/SignInModal.tsx
  fe/src/components/block/navbar/DefaultTab.tsx
  fe/src/components/block/sideBar/SideBar.tsx
  fe/src/hooks/common/useMovePage.ts
  fe/src/hooks/query/commnent/useGetBelowComments.ts
  fe/src/hooks/query/member/useCheckEmailApprove.ts
  fe/src/page/APITestPage.tsx
  fe/src/page/AccountLinking.tsx
  fe/src/page/BlackNoteTest.tsx
  fe/src/page/Main.tsx
  fe/src/page/RegisterEmail.tsx
  fe/src/page/TestPage.tsx
  fe/src/routes/router.tsx
  fe/src/store/useTabStore.ts
Labels: 프런트, PROGRESS
