Repository sgdevcamp2023/recycle, pull requests merged in 2024-02, with the labels that each got.

#245 [Fe/#244] router 방식, Refer 적용을 위해서 수정
  fe/src/components/block/sideBar/SideBar.tsx
  fe/src/page/Common.tsx
  fe/src/routes/router.tsx
  fe/src/store/useTabStore.ts
Labels: 프런트

#247 [Fe/#240] 회원가입 기능구현
  fe/src/components/atom/Button/DefaultButton.tsx
  fe/src/components/block/modal/SignInModal.tsx
  fe/src/hooks/common/useMovePage.ts
  fe/src/hooks/query/member/useSignUp.ts
  fe/src/routes/router.tsx
Labels: 프런트

#261 [Fe/#260] Markdown Editor - CodeComment setting
  fe/package-lock.json
  fe/package.json
  fe/src/page/MarkdownEditor.tsx
Labels: 프런트

#198 [Be/#160] Feat: read member
  be/docs/comment/DEVELOP.md
  be/docs/member/API.md
  be/docs/member/ARCHITECTURE.md
  be/docs/member/DEVELOP.md
  be/docs/member/EVENT.md
  be/docs/notification/ARCHITECTURE.md
  be/docs/question/API.md
  be/docs/question/ARCHITECTURE.md
  be/docs/question/DEVELOP.md
  be/docs/question/EVENT.md
  be/docs/review/API.md
  be/docs/review/DEVELOP.md
  be/docs/review/EVENT.md
  be/member-api/src/main/java/com/zzaug/member/domain/dto/member/MemberResponse.java
  be/member-api/src/main/java/com/zzaug/member/domain/exception/DBSource.java
  be/member-api/src/main/java/com/zzaug/member/domain/exception/SourceNotFoundException.java
  be/member-api/src/main/java/com/zzaug/member/domain/external/dao/member/ExternalContactDao.java
  be/member-api/src/main/java/com/zzaug/member/domain/external/dao/member/MemberDao.java
  be/member-api/src/main/java/com/zzaug/member/domain/external/dao/member/MemberDaoImpl.java
  be/member-api/src/main/java/com/zzaug/member/domain/external/dao/member/MemberSourceDao.java
  be/member-api/src/main/java/com/zzaug/member/domain/external/service/member/MemberSourceQuery.java
  be/member-api/src/main/java/com/zzaug/member/domain/external/service/member/RegularMemberSourceQuery.java
  be/member-api/src/main/java/com/zzaug/member/domain/model/member/MemberSource.java
  be/member-api/src/main/java/com/zzaug/member/domain/support/entity/MemberEntityConverter.java
  be/member-api/src/main/java/com/zzaug/member/domain/usecase/member/GetMemberUseCase.java
  be/member-api/src/main/java/com/zzaug/member/domain/usecase/member/MemberConverter.java
  be/member-api/src/main/java/com/zzaug/member/domain/usecase/member/MemberUseCase.java
  be/member-api/src/main/java/com/zzaug/member/domain/util/UtilSomething.java
  be/member-api/src/main/java/com/zzaug/member/web/controller/v1/member/MemberController.java
  be/member-api/src/main/java/com/zzaug/member/web/dto/validator/PositiveId.java
  be/member-api/src/main/java/com/zzaug/member/web/dto/validator/PositiveIdValidator.java
  be/member-api/src/main/java/com/zzaug/member/web/handler/MemberApiExceptionHandler.java
  be/member-api/src/test/java/com/zzaug/member/domain/usecase/AbstractUseCaseTest.java
  be/member-api/src/test/java/com/zzaug/member/domain/usecase/config/TestLocalDateTimeBaseEntity.java
  be/member-api/src/test/java/com/zzaug/member/domain/usecase/config/mock/repository/UMockExternalContactDao.java
  be/member-api/src/test/java/com/zzaug/member/domain/usecase/config/mock/service/UMockMemberSourceQuery.java
  be/member-api/src/test/java/com/zzaug/member/domain/usecase/member/GetMemberUseCaseTest.java
  be/rabbitmq/src/main/java/com/zzaug/rabbitmq/listener/dead/DeadLetterListener.java
  be/rabbitmq/src/main/java/com/zzaug/rabbitmq/listener/dead/DeadLetterMapper.java
  be/review-api/src/main/java/com/zzaug/review/web/controller/v1/review/ReviewController.java
Labels: 백엔드

#277 [Be/#171] Feat: web logging
  be/web/build.gradle
  be/web/src/main/resources/logback-spring.xml
Labels: 백엔드

#200 [Be/#162] Feat: certification check
  be/member-api/src/main/java/com/zzaug/member/domain/usecase/member/CheckDuplicationUseCase.java
  be/member-api/src/main/java/com/zzaug/member/web/controller/v1/member/MemberCheckController.java
  be/member-api/src/test/java/com/zzaug/member/domain/usecase/member/CheckDuplicationUseCaseTest.java
  be/member-api/src/test/java/com/zzaug/member/domain/usecase/member/CheckDuplicationUseCaseTest_EXIST_CERTIFICATION.java
  be/member-api/src/test/java/com/zzaug/member/web/controller/v1/member/MemberCheckControllerTest.java
  be/security/src/main/java/com/zzaug/security/config/WebSecurityConfig.java
Labels: 백엔드

#202 [Be/#164] Feat: check email auth
  be/docs/member/API.md
  be/member-api/src/main/java/com/zzaug/member/domain/dto/member/CheckEmailAuthUseCaseRequest.java
  be/member-api/src/main/java/com/zzaug/member/domain/dto/member/CheckEmailAuthUseCaseResponse.java
  be/member-api/src/main/java/com/zzaug/member/domain/event/AddEmailEvent.java
  be/member-api/src/main/java/com/zzaug/member/domain/exception/DBSource.java
  be/member-api/src/main/java/com/zzaug/member/domain/exception/InvalidRequestException.java
  be/member-api/src/main/java/com/zzaug/member/domain/exception/OverMaxTryCountException.java
  be/member-api/src/main/java/com/zzaug/member/domain/exception/SourceNotFoundException.java
  be/member-api/src/main/java/com/zzaug/member/domain/external/dao/auth/EmailAuthDao.java
  be/member-api/src/main/java/com/zzaug/member/domain/external/dao/auth/EmailAuthDaoImpl.java
  be/member-api/src/main/java/com/zzaug/member/domain/external/dao/log/EmailAuthLogDao.java
  be/member-api/src/main/java/com/zzaug/member/domain/external/dao/log/EmailAuthLogDaoImpl.java
  be/member-api/src/main/java/com/zzaug/member/domain/external/dao/member/AuthenticationDao.java
  be/member-api/src/main/java/com/zzaug/member/domain/external/dao/member/ExternalContactDao.java
  be/member-api/src/main/java/com/zzaug/member/domain/external/dao/member/MemberDaoImpl.java
  be/member-api/src/main/java/com/zzaug/member/domain/external/service/auth/EmailAuthLogCommand.java
  be/member-api/src/main/java/com/zzaug/member/domain/external/service/auth/EmailAuthLogCommandImpl.java
  be/member-api/src/main/java/com/zzaug/member/domain/external/service/auth/EmailAuthLogService.java
  be/member-api/src/main/java/com/zzaug/member/domain/model/auth/EmailAuthResult.java
  be/member-api/src/main/java/com/zzaug/member/domain/model/auth/EmailAuthSource.java
  be/member-api/src/main/java/com/zzaug/member/domain/model/auth/TryCountElement.java
  be/member-api/src/main/java/com/zzaug/member/domain/support/entity/EmailAuthSourceConverter.java
  be/member-api/src/main/java/com/zzaug/member/domain/usecase/member/CheckEmailAuthUseCase.java
  be/member-api/src/main/java/com/zzaug/member/web/controller/v1/member/MemberCheckController.java
  be/member-api/src/main/java/com/zzaug/member/web/dto/member/CheckEmailAuthRequest.java
  be/member-api/src/main/java/com/zzaug/member/web/handler/MemberApiExceptionHandler.java
  be/member-api/src/test/java/com/zzaug/member/domain/usecase/config/mock/repository/UMockEmailAuthDao.java
  be/member-api/src/test/java/com/zzaug/member/domain/usecase/config/mock/repository/UMockEmailAuthLogDao.java
  be/member-api/src/test/java/com/zzaug/member/domain/usecase/config/mock/repository/UMockExternalContactDao.java
  be/member-api/src/test/java/com/zzaug/member/domain/usecase/member/CheckEmailAuthUseCaseTest.java
  be/member-api/src/test/java/com/zzaug/member/domain/usecase/member/CheckEmailAuthUseCaseTest_OVER_MAX_TRYCOUNT.java
  be/member-api/src/test/java/com/zzaug/member/domain/usecase/member/CheckEmailAuthUseCaseTest_UNDER_MAX_TRYCOUNT.java
  be/member-api/src/test/java/com/zzaug/member/redis/email/EmailAuthSessionRepositoryTest.java
Labels: 백엔드

#203 [Be/#165] Feat: edit member
  be/member-api/src/main/java/com/zzaug/member/domain/dto/member/MemberUseCaseRequest.java
  be/member-api/src/main/java/com/zzaug/member/domain/event/UpdateMemberEvent.java
  be/member-api/src/main/java/com/zzaug/member/domain/exception/PasswordNotMatchException.java
  be/member-api/src/main/java/com/zzaug/member/domain/model/member/MemberAuthentication.java
  be/member-api/src/main/java/com/zzaug/member/domain/support/entity/MemberAuthenticationConverter.java
  be/member-api/src/main/java/com/zzaug/member/domain/usecase/member/UpdateMemberUseCase.java
  be/member-api/src/main/java/com/zzaug/member/web/controller/v1/member/MemberController.java
  be/member-api/src/main/java/com/zzaug/member/web/handler/MemberApiExceptionHandler.java
  be/member-api/src/main/java/com/zzaug/member/web/support/usecase/MemberUseCaseRequestConverter.java
  be/member-api/src/test/java/com/zzaug/member/domain/usecase/config/mock/repository/UMockAuthenticationDao.java
  be/member-api/src/test/java/com/zzaug/member/domain/usecase/member/UpdateMemberUseCaseTest.java
  be/member-api/src/test/java/com/zzaug/member/domain/usecase/member/UpdateMemberUseCaseTest_EXIST_CERTIFICATION.java
Labels: 백엔드

#204 [Be/#166] Feat: delete member
  be/member-api/src/main/java/com/zzaug/member/domain/event/WithDrawnMemberEvent.java
  be/member-api/src/main/java/com/zzaug/member/domain/usecase/member/DeleteMemberUseCase.java
  be/member-api/src/main/java/com/zzaug/member/web/controller/v1/member/MemberController.java
  be/member-api/src/test/java/com/zzaug/member/domain/usecase/member/DeleteMemberUseCaseTest.java
Labels: 백엔드

#231 [Be/#169] Feat: renewal token
  be/member-api/src/main/java/com/zzaug/member/domain/dto/member/RenewalTokenUseCaseRequest.java
  be/member-api/src/main/java/com/zzaug/member/domain/external/dao/auth/BlackTokenAuthDao.java
  be/member-api/src/main/java/com/zzaug/member/domain/external/dao/auth/BlackTokenAuthDaoImpl.java
  be/member-api/src/main/java/com/zzaug/member/domain/usecase/member/RenewalTokenUseCase.java
  be/member-api/src/main/java/com/zzaug/member/web/controller/v1/member/MemberController.java
  be/member-api/src/test/java/com/zzaug/member/domain/usecase/config/mock/repository/UMockBlackTokenAuthDao.java
  be/member-api/src/test/java/com/zzaug/member/domain/usecase/member/LoginUseCaseTest.java
  be/member-api/src/test/java/com/zzaug/member/domain/usecase/member/RenewalTokenUseCaseTest.java
  be/member-api/src/test/java/com/zzaug/member/domain/usecase/validator/MemberAuthTokenValidator.java
  be/member-api/src/test/java/com/zzaug/member/web/controller/v1/member/MemberControllerTest.java
Labels: 백엔드

#232 [Be/#170] Feat: search ceritifcation
  be/member-api/src/main/java/com/zzaug/member/domain/model/member/GetMemberId.java
  be/member-api/src/main/java/com/zzaug/member/domain/model/member/MemberAuthentication.java
  be/member-api/src/main/java/com/zzaug/member/domain/usecase/member/SearchMemberUseCase.java
  be/member-api/src/main/java/com/zzaug/member/web/controller/v1/member/MemberController.java
  be/member-api/src/test/java/com/zzaug/member/domain/usecase/config/mock/repository/UMockAuthenticationDao.java
  be/member-api/src/test/java/com/zzaug/member/domain/usecase/member/SearchMemberUseCaseTest.java
  be/member-api/src/test/java/com/zzaug/member/domain/usecase/member/SearchMemberUseCaseTest_NOT_EXIST_CERTIFICATION.java
Labels: 백엔드

#252 [Be/#250] Refactor: controller
  be/member-api/src/main/java/com/zzaug/member/domain/dto/member/MemberAuthToken.java
  be/member-api/src/main/java/com/zzaug/member/web/controller/v1/member/MemberCheckController.java
  be/member-api/src/main/java/com/zzaug/member/web/controller/v1/member/MemberController.java
  be/member-api/src/main/java/com/zzaug/member/web/dto/member/LoginRequest.java
  be/member-api/src/test/java/com/zzaug/member/domain/usecase/config/mock/repository/UMockEmailAuthDao.java
  be/member-api/src/test/java/com/zzaug/member/domain/usecase/member/CheckEmailAuthUseCaseTest_OVER_MAX_TRYCOUNT.java
  be/member-api/src/test/java/com/zzaug/member/domain/usecase/member/CheckEmailAuthUseCaseTest_UNDER_MAX_TRYCOUNT.java
  be/member-api/src/test/java/com/zzaug/member/domain/usecase/member/LoginUseCaseTest.java
  be/member-api/src/test/java/com/zzaug/member/domain/usecase/member/RenewalTokenUseCaseTest.java
  be/member-api/src/test/java/com/zzaug/member/domain/usecase/member/UpdateMemberUseCaseTest.java
  be/member-api/src/test/java/com/zzaug/member/domain/usecase/member/UpdateMemberUseCaseTest_EXIST_CERTIFICATION.java
  be/member-api/src/test/java/com/zzaug/member/web/controller/v1/description/Description.java
  be/member-api/src/test/java/com/zzaug/member/web/controller/v1/member/MemberCheckControllerTest.java
  be/member-api/src/test/java/com/zzaug/member/web/controller/v1/member/MemberControllerTest.java
  be/web/src/main/java/com/zzaug/web/support/ApiResponse.java
Labels: 백엔드

#268 [Be/#267] Fix: 추가 빠진 @Transactional 어노테이션
  be/member-api/src/main/java/com/zzaug/member/domain/usecase/member/CheckDuplicationUseCase.java
  be/member-api/src/main/java/com/zzaug/member/domain/usecase/member/LogOutUseCase.java
  be/member-api/src/main/java/com/zzaug/member/domain/usecase/member/LoginUseCase.java
  be/member-api/src/main/java/com/zzaug/member/domain/usecase/member/SearchMemberUseCase.java
Labels: 백엔드

#281 [Be/#275] Refactor: remove annotation for test
  be/member-api/build.gradle
  be/member-api/src/main/java/com/zzaug/member/web/controller/v1/member/MemberCheckController.java
  be/member-api/src/main/java/com/zzaug/member/web/controller/v1/member/MemberController.java
  be/member-api/src/test/java/com/zzaug/member/web/controller/config/TestTokenUserDetailsService.java
  be/member-api/src/test/java/com/zzaug/member/web/controller/v1/member/MemberCheckControllerTest.java
  be/member-api/src/test/java/com/zzaug/member/web/controller/v1/member/MemberControllerTest.java
Labels: 백엔드

#282 [Be/#276] Chore: setting for docker image
  be/member-api/Dockerfile
  be/member-api/build.gradle
Labels: 백엔드

#288 [BE/#284] Feat: 추가 EnableRabbit
  be/rabbitmq/src/main/java/com/zzaug/rabbitmq/config/ZRabbiMQConfig.java
Labels: 백엔드

#299 [Fe/298] ReviewWriteModal 구현
  fe/package-lock.json
  fe/package.json
  fe/src/components/block/modal/ReviewWriteModal.tsx
  fe/src/page/MarkdownEditor.tsx
  fe/src/page/TestPageThree.tsx
  fe/src/routes/router.tsx
Labels: 프런트

#300 [Fe/#270] line comment
  fe/src/hooks/common/test.tsx
  fe/src/hooks/common/useTextSelction.ts
  fe/src/page/LineComment.tsx
  fe/src/page/PopOver.tsx
  fe/src/routes/router.tsx
Labels: 프런트

#305 [Fe/301] ReviewShowModal 구현
  fe/src/components/block/modal/ReviewShowModal.tsx
  fe/src/page/TestPageThree.tsx
  fe/src/routes/router.tsx
Labels: 프런트

#308 [Fe/#307] lineComment react-md-editor 적용 가능 한지 테스트
  fe/src/components/block/Content/CreateQuestion.tsx
  fe/src/page/Common.tsx
  fe/src/routes/router.tsx
  fe/src/store/useTabStore.ts
Labels: 프런트

#310 Be/#302 set bean name
  be/member-api/src/main/java/com/zzaug/member/config/MemberAppConfig.java
  be/rabbitmq/src/main/java/com/zzaug/rabbitmq/config/ZRMQConnectionConfig.java
  be/rabbitmq/src/main/java/com/zzaug/rabbitmq/config/ZRMQListenerConfig.java
  be/rabbitmq/src/main/java/com/zzaug/rabbitmq/config/ZRabbiMQConfig.java
  be/security/src/main/java/com/zzaug/security/config/SecurityConfig.java
Labels: 백엔드

#311 [Be/#303] Refactor: remove redis auto config
  be/member-api/src/main/java/com/zzaug/member/config/RedisConfig.java
  be/security/src/main/java/com/zzaug/security/config/SecurityConfig.java
Labels: 백엔드

#313 [BE/#312] Fix: timestamp 직렬화 문제
  be/web/src/main/java/com/zzaug/web/support/ApiResponse.java
Labels: 백엔드

#294 [Be/#289] Feat: record invalid access token
  be/flyway/src/main/resources/db/migration/entity/member/V1.00.0.11__drop_invalid_access_token_log_tables.sql
  be/flyway/src/main/resources/db/migration/entity/security/V4.00.0.1__init_invalid_access_token_log_tables.sql
  be/member-api/src/main/java/com/zzaug/member/entity/BlackTokenAuthFKBaseEntity.java
  be/member-api/src/main/java/com/zzaug/member/entity/auth/BlackTokenAuthEntity.java
  be/member-api/src/main/java/com/zzaug/member/entity/auth/TokenData.java
  be/member-api/src/main/java/com/zzaug/member/entity/auth/TokenDataConverter.java
  be/member-api/src/main/java/com/zzaug/member/entity/auth/TokenType.java
  be/security/src/main/java/com/zzaug/security/authentication/token/TokenUserDetailsService.java
  be/security/src/main/java/com/zzaug/security/config/WebSecurityConfig.java
  be/security/src/main/java/com/zzaug/security/entity/log/InvalidTokenAccessEntity.java
  be/security/src/main/java/com/zzaug/security/event/InvalidAccessTokenEventService.java
  be/security/src/main/java/com/zzaug/security/event/InvalidTokenAccessEvent.java
  be/security/src/main/java/com/zzaug/security/filter/exception/TokenInvalidExceptionHandlerFilter.java
  be/security/src/main/java/com/zzaug/security/persistence/log/InvalidTokenAccessRepository.java
  be/web/src/main/java/com/zzaug/web/handler/ApiControllerExceptionHandler.java
Labels: 백엔드

#295 [Be/#290] Fix: custom transactional
  be/member-api/src/main/java/com/zzaug/member/persistence/support/transaction/UseCaseTransactional.java
  be/security/src/main/java/com/zzaug/security/persistence/transaction/SecurityTransactional.java
Labels: 백엔드

#286 [Be/#49] review api docs 수정 사항 반영
  be/docs/comment/API.md
  be/docs/question/API.md
  be/docs/question/EVENT.md
  be/docs/review/API.md
  be/docs/review/EVENT.md
Labels: 백엔드, 문서

#321 [Be/#315] Refactor: white token add memberId effect
  be/member-api/src/main/java/com/zzaug/member/domain/external/security/auth/EnrollBlackTokenCacheServiceImpl.java
  be/member-api/src/main/java/com/zzaug/member/domain/external/security/auth/EnrollTokenCacheService.java
  be/member-api/src/main/java/com/zzaug/member/domain/external/security/auth/EnrollWhiteAccessTokenCacheServiceImpl.java
  be/member-api/src/main/java/com/zzaug/member/domain/external/security/auth/EnrollWhiteTokenCacheServiceImpl.java
  be/member-api/src/main/java/com/zzaug/member/domain/external/security/auth/ReplaceTokenCacheService.java
  be/member-api/src/main/java/com/zzaug/member/domain/external/security/auth/ReplaceWhiteAccessTokenCacheServiceImpl.java
  be/member-api/src/main/java/com/zzaug/member/domain/usecase/member/CheckEmailAuthUseCase.java
  be/member-api/src/main/java/com/zzaug/member/domain/usecase/member/EmailAuthUseCase.java
  be/member-api/src/main/java/com/zzaug/member/domain/usecase/member/LoginUseCase.java
  be/member-api/src/main/java/com/zzaug/member/domain/usecase/member/PostMemberUseCase.java
  be/member-api/src/main/java/com/zzaug/member/domain/usecase/member/RenewalTokenUseCase.java
  be/member-api/src/main/java/com/zzaug/member/domain/usecase/member/UpdateMemberUseCase.java
  be/member-api/src/test/java/com/zzaug/member/domain/usecase/config/mock/security/UMockEnrollTokenCacheService.java
  be/member-api/src/test/java/com/zzaug/member/domain/usecase/config/mock/security/UMockReplaceTokenCacheService.java
  be/security/src/main/java/com/zzaug/security/redis/auth/BlackAuthTokenHash.java
Labels: 백엔드

#322 Be/#316 email auth function
  be/member-api/src/main/java/com/zzaug/member/domain/eventlistener/EmailAuthEventListener.java
  be/member-api/src/main/resources/application-dev.yml
  be/member-api/src/main/resources/application-local.yml
  be/member-api/src/main/resources/application-prod.yml
  be/member-api/src/main/resources/application.yml
  be/notification-api/build.gradle
  be/notification-api/src/main/java/com/zzaug/notification/config/MaliConfig.java
  be/notification-api/src/main/java/com/zzaug/notification/config/NotificationAppConfig.java
  be/notification-api/src/main/java/com/zzaug/notification/config/NotificationJpaDataSourceConfig.java
  be/notification-api/src/main/java/com/zzaug/notification/config/NotificationMysqlConfig.java
  be/notification-api/src/main/java/com/zzaug/notification/email/dto/AuthEmailDto.java
  be/notification-api/src/main/java/com/zzaug/notification/email/listener/auth/email/EmailAuthRequestListener.java
  be/notification-api/src/main/java/com/zzaug/notification/email/listener/auth/email/EmailAuthRequestListnerConfig.java
  be/notification-api/src/main/java/com/zzaug/notification/email/listener/auth/email/EmailAuthRequestMapper.java
  be/notification-api/src/main/java/com/zzaug/notification/email/service/SendEmailAuthService.java
  be/notification-api/src/main/resources/application-dev.yml
  be/notification-api/src/main/resources/application-local.yml
  be/notification-api/src/main/resources/application-mail-dev.yml
  be/notification-api/src/main/resources/application-mail-local.yml
  be/notification-api/src/main/resources/application-mail-prod.yml
  be/notification-api/src/main/resources/application-mail.yml
  be/notification-api/src/main/resources/application-mysql.yml
  be/notification-api/src/main/resources/application-prod.yml
  be/notification-api/src/main/resources/application.yml
  be/notification-api/src/main/resources/templates/email-auth.html
  be/rabbitmq/src/main/java/com/zzaug/rabbitmq/config/ZRMQProperties.java
  be/rabbitmq/src/main/java/com/zzaug/rabbitmq/config/queue/NotificationQConfig.java
Labels: 백엔드

#324 [Be/#318] Fix: invalidtokenacessentity
  be/security/src/main/java/com/zzaug/security/entity/log/InvalidTokenAccessEntity.java
Labels: 백엔드

#326 [Fe/#309] 질문글 작성, 게시하기, 리뷰하기 기능 구현
  fe/src/components/block/Content/CreateQuestion.tsx
  fe/src/components/block/Content/CreateReview.tsx
  fe/src/components/block/modal/ReviewWriteModal.tsx
  fe/src/components/layout/GridTemplate.tsx
  fe/src/page/Common.tsx
  fe/src/routes/router.tsx
  fe/src/store/useMarkdownStore.ts
  fe/src/store/useQuestionStore.ts
  fe/src/store/useReviewStore.ts
Labels: 높음, 프런트

#343 [Fe/342] input design refactor
  fe/src/components/block/modal/ErrorModal.tsx
  fe/src/components/block/modal/LoginModal.tsx
  fe/src/components/block/modal/RegisterEmailModal.tsx
  fe/src/components/block/modal/ShowReviewerModal.tsx
  fe/src/components/block/modal/SignInModal.tsx
  fe/src/page/TestPageThree.tsx
Labels: 프런트

#327 [Be/#179] Feat: reviewquery server question command
  be/review-query-api/build.gradle
  be/review-query-api/src/main/java/com/zzaug/review/config/ElasticSearchConfig.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/dto/question/query/QuestionQueryCreateUseCaseRequest.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/dto/question/query/QuestionQueryDeleteUseCaseRequest.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/dto/question/query/QuestionQueryEditUseCaseRequest.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/model/question/query/QuestionQuery.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/persistence/question/QuestionQueryRepository.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/support/entity/QuestionQueryEntityConverter.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/usecase/question/query/QuestionQueryConverter.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/usecase/question/query/QuestionQueryCreateUseCase.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/usecase/question/query/QuestionQueryDeleteUseCase.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/usecase/question/query/QuestionQueryEditUseCase.java
  be/review-query-api/src/main/java/com/zzaug/review/entity/question/query/QuestionQueryEntity.java
  be/review-query-api/src/main/resources/application-elasticsearch-local.yml
  be/review-query-api/src/main/resources/application-local.yml
  be/review-query-api/src/main/resources/elasticsearch/mappings/question-mapping.json
  be/review-query-api/src/main/resources/elasticsearch/settings/question-setting.json
Labels: 백엔드

#329 [Be/#195] Feat: reviewquery server question query
  be/review-query-api/src/main/java/com/zzaug/review/config/ReviewAppConfig.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/dto/question/query/QuestionQueryResponse.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/dto/question/query/QuestionQuerySearchUseCaseRequest.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/dto/question/query/QuestionQueryViewUseCaseRequest.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/dto/question/query/QuestionTempQueryResponse.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/dto/review/query/ReviewQueryResponse.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/dto/review/query/ReviewQueryUseCaseRequest.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/dto/review/query/ReviewTempQueryResponse.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/model/review/ReviewType.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/model/review/query/ReviewQuery.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/persistence/review/ReviewQueryRepository.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/support/entity/ReviewQueryEntityConverter.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/usecase/question/query/QuestionQueryResponseConverter.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/usecase/question/query/QuestionQuerySearchUseCase.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/usecase/question/query/QuestionQueryViewUseCase.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/usecase/review/query/ReviewQueryConverter.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/usecase/review/query/ReviewQueryUseCase.java
  be/review-query-api/src/main/java/com/zzaug/review/entity/review/query/ReviewQueryEntity.java
  be/review-query-api/src/main/java/com/zzaug/review/exception/ExternalIntegrationException.java
  be/review-query-api/src/main/java/com/zzaug/review/exception/JsonParsingException.java
  be/review-query-api/src/main/java/com/zzaug/review/support/ApiResponse.java
  be/review-query-api/src/main/java/com/zzaug/review/support/ApiResponseGenerator.java
  be/review-query-api/src/main/java/com/zzaug/review/support/FailureBodyResolver.java
  be/review-query-api/src/main/java/com/zzaug/review/support/MessageCode.java
  be/review-query-api/src/main/java/com/zzaug/review/support/MessageSourceAccessor.java
  be/review-query-api/src/main/java/com/zzaug/review/support/Page.java
  be/review-query-api/src/main/java/com/zzaug/review/web/controller/v1/MeQueryController.java
  be/review-query-api/src/main/java/com/zzaug/review/web/controller/v1/QuestionQueryController.java
  be/review-query-api/src/main/java/com/zzaug/review/web/controller/v1/ReviewQueryController.java
  be/review-query-api/src/main/java/com/zzaug/review/web/dto/question/query/QuestionQuerySearchRequest.java
  be/review-query-api/src/main/java/com/zzaug/review/web/dto/question/query/QuestionQueryViewRequest.java
  be/review-query-api/src/main/java/com/zzaug/review/web/dto/review/query/ReviewQueryRequest.java
  be/review-query-api/src/main/java/com/zzaug/review/web/support/usecase/QuestionQuerySearchUseCaseRequestConverter.java
  be/review-query-api/src/main/java/com/zzaug/review/web/support/usecase/QuestionQueryViewUseCaseRequestConverter.java
  be/review-query-api/src/main/java/com/zzaug/review/web/support/usecase/ReviewUseCaseRequestConverter.java
  be/review-query-api/src/test/java/com/zzaug/review/web/controller/v1/MeQueryControllerTest.java
  be/review-query-api/src/test/java/com/zzaug/review/web/controller/v1/QuestionQueryControllerTest.java
  be/review-query-api/src/test/java/com/zzaug/review/web/controller/v1/ReviewQueryControllerTest.java
  be/review-query-api/src/test/java/com/zzaug/review/web/controller/v1/description/Description.java
  be/review-query-api/src/test/java/com/zzaug/review/web/controller/v1/description/QuestionDescription.java
  be/review-query-api/src/test/java/com/zzaug/review/web/controller/v1/description/ReviewDescription.java
Labels: 백엔드

#330 [Be/#212] Feat: reviewquery server review query
  be/review-query-api/src/main/java/com/zzaug/review/domain/dto/review/query/ReviewByQuestionUseCaseRequest.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/dto/review/query/SearchByQuestionUseCaseRequest.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/dto/review/query/SearchByReviewUseCaseRequest.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/usecase/review/query/ReviewByQuestionUseCase.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/usecase/review/query/ReviewQueryResponseConverter.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/usecase/review/query/SearchByQuestionUseCase.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/usecase/review/query/SearchByReviewUseCase.java
  be/review-query-api/src/main/java/com/zzaug/review/entity/review/query/ReviewPoint.java
  be/review-query-api/src/main/java/com/zzaug/review/web/dto/review/query/ReviewSearchByQuestionRequest.java
  be/review-query-api/src/main/java/com/zzaug/review/web/dto/review/query/ReviewSearchRequest.java
  be/review-query-api/src/main/java/com/zzaug/review/web/support/usecase/ReviewByQuestionUseCaseRequestConverter.java
  be/review-query-api/src/main/java/com/zzaug/review/web/support/usecase/SearchByQuestionUseCaseRequestConverter.java
  be/review-query-api/src/main/java/com/zzaug/review/web/support/usecase/SearchByReviewUseCaseRequestConverter.java
  be/review-query-api/src/main/resources/elasticsearch/mappings/review-mapping.json
  be/review-query-api/src/main/resources/elasticsearch/settings/review-setting.json
Labels: 백엔드

#331 [Be/#225] Feat: reviewquery server my query
  be/review-query-api/build.gradle
  be/review-query-api/src/main/java/com/zzaug/review/domain/dto/review/query/ViewMemberQuestionUseCaseRequest.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/dto/review/query/ViewMemberReviewUseCaseRequest.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/usecase/question/query/ViewMemberQuestionUseCase.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/usecase/review/query/ViewMemberReviewUseCase.java
  be/review-query-api/src/main/java/com/zzaug/review/web/controller/v1/MeQueryController.java
  be/review-query-api/src/main/java/com/zzaug/review/web/support/usecase/ViewMemberQuestionUseCaseRequestConverter.java
  be/review-query-api/src/main/java/com/zzaug/review/web/support/usecase/ViewMemberReviewUseCaseRequestConverter.java
  be/review-query-api/src/main/resources/application-local.yml
  be/web/src/main/java/com/zzaug/web/support/ApiResponseGenerator.java
Labels: 백엔드

#333 [Be/#269] Feat: review domain create event
  be/review-api/src/main/java/com/zzaug/review/domain/event/review/DeleteReviewEvent.java
  be/review-api/src/main/java/com/zzaug/review/domain/event/review/EditReviewEvent.java
  be/review-api/src/main/java/com/zzaug/review/domain/event/review/SaveReviewEvent.java
  be/review-api/src/main/java/com/zzaug/review/domain/persistence/member/ReviewerListRepository.java
  be/review-api/src/main/java/com/zzaug/review/domain/persistence/question/QuestionRepository.java
  be/review-api/src/main/java/com/zzaug/review/domain/persistence/review/ReviewRepository.java
  be/review-api/src/main/java/com/zzaug/review/domain/support/entity/ReviewerListEntityConverter.java
  be/review-api/src/main/java/com/zzaug/review/domain/usecase/review/ReviewCreateUseCase.java
  be/review-api/src/main/java/com/zzaug/review/domain/usecase/review/ReviewDeleteUseCase.java
  be/review-api/src/main/java/com/zzaug/review/domain/usecase/review/ReviewEditUseCase.java
  be/review-api/src/main/java/com/zzaug/review/domain/usecase/review/ReviewTempCreateUseCase.java
  be/review-api/src/main/java/com/zzaug/review/domain/usecase/review/ReviewTempViewUseCase.java
  be/review-api/src/main/java/com/zzaug/review/domain/usecase/review/event/ReviewEventService.java
  be/review-api/src/main/java/com/zzaug/review/domain/usecase/review/event/converter/DeleteReviewEventConverter.java
  be/review-api/src/main/java/com/zzaug/review/domain/usecase/review/event/converter/EditReviewEventConverter.java
  be/review-api/src/main/java/com/zzaug/review/domain/usecase/review/event/converter/SaveReviewEventConverter.java
  be/review-api/src/main/java/com/zzaug/review/entity/question/QuestionEntity.java
  be/review-api/src/main/java/com/zzaug/review/entity/review/ReviewEntity.java
Labels: 백엔드

#334 [Be/#292] reviewquery server question domain event
  be/review-query-api/build.gradle
  be/review-query-api/src/main/java/com/zzaug/review/domain/dto/question/query/QuestionQueryEditUseCaseRequest.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/event/question/DeleteQuestionEvent.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/event/question/SaveQuestionEvent.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/model/question/query/QuestionQuery.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/persistence/question/QuestionQueryRepository.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/support/entity/QuestionQueryEntityConverter.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/usecase/question/event/QuestionEventListener.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/usecase/question/query/QuestionQueryConverter.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/usecase/question/query/QuestionQueryCreateUseCase.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/usecase/question/query/QuestionQueryDeleteUseCase.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/usecase/question/query/QuestionQueryEditUseCase.java
  be/review-query-api/src/main/java/com/zzaug/review/entity/question/query/QuestionQueryEntity.java
  be/review-query-api/src/main/resources/application-local.yml
  be/review-query-api/src/main/resources/elasticsearch/mappings/question-mapping.json
Labels: 백엔드

#335 [Be/#293] Feat: reviewquery server review event
  be/review-query-api/build.gradle
  be/review-query-api/src/main/java/com/zzaug/review/domain/dto/question/query/QuestionQueryEditUseCaseRequest.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/dto/review/query/ReviewQueryCreateUseCaseRequest.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/dto/review/query/ReviewQueryDeleteUseCaseRequest.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/dto/review/query/ReviewQueryEditUseCaseRequest.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/event/question/DeleteQuestionEvent.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/event/question/SaveQuestionEvent.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/event/review/DeleteReviewEvent.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/event/review/EditReviewEvent.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/event/review/SaveReviewEvent.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/model/question/query/QuestionQuery.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/persistence/question/QuestionQueryRepository.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/support/entity/QuestionQueryEntityConverter.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/usecase/question/event/QuestionEventListener.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/usecase/question/query/QuestionQueryConverter.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/usecase/question/query/QuestionQueryCreateUseCase.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/usecase/question/query/QuestionQueryDeleteUseCase.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/usecase/question/query/QuestionQueryEditUseCase.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/usecase/review/event/ReviewEventListener.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/usecase/review/query/ReviewQueryConverter.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/usecase/review/query/ReviewQueryCreateUseCase.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/usecase/review/query/ReviewQueryDeleteUseCase.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/usecase/review/query/ReviewQueryEditUseCase.java
  be/review-query-api/src/main/java/com/zzaug/review/entity/question/query/QuestionQueryEntity.java
  be/review-query-api/src/main/resources/application-local.yml
  be/review-query-api/src/main/resources/elasticsearch/mappings/question-mapping.json
  be/review-query-api/src/main/resources/elasticsearch/mappings/review-mapping.json
Labels: 백엔드

#345 [Be/#212] reviewquery review query
  be/review-query-api/build.gradle
  be/review-query-api/src/main/java/com/zzaug/review/domain/dto/review/query/ReviewQueryCreateUseCaseRequest.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/dto/review/query/ReviewQueryDeleteUseCaseRequest.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/dto/review/query/ReviewQueryEditUseCaseRequest.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/dto/review/query/ViewMemberQuestionUseCaseRequest.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/dto/review/query/ViewMemberReviewUseCaseRequest.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/event/review/DeleteReviewEvent.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/event/review/EditReviewEvent.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/event/review/SaveReviewEvent.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/usecase/question/query/ViewMemberQuestionUseCase.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/usecase/review/event/ReviewEventListener.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/usecase/review/query/ReviewQueryConverter.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/usecase/review/query/ReviewQueryCreateUseCase.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/usecase/review/query/ReviewQueryDeleteUseCase.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/usecase/review/query/ReviewQueryEditUseCase.java
  be/review-query-api/src/main/java/com/zzaug/review/domain/usecase/review/query/ViewMemberReviewUseCase.java
  be/review-query-api/src/main/java/com/zzaug/review/web/controller/v1/MeQueryController.java
  be/review-query-api/src/main/java/com/zzaug/review/web/support/usecase/ViewMemberQuestionUseCaseRequestConverter.java
  be/review-query-api/src/main/java/com/zzaug/review/web/support/usecase/ViewMemberReviewUseCaseRequestConverter.java
  be/review-query-api/src/main/resources/application-local.yml
  be/review-query-api/src/main/resources/elasticsearch/mappings/review-mapping.json
  be/web/src/main/java/com/zzaug/web/support/ApiResponseGenerator.java
Labels: 백엔드

#347 [Fe/#340] line comment apply
  fe/src/components/atom/Comment/LineCommentView.tsx
  fe/src/components/atom/Comment/LineCommentWrite.tsx
  fe/src/components/block/Content/CreateReview.tsx
  fe/src/components/block/Content/Question.tsx
  fe/src/components/block/Content/ReadQuestion.tsx
  fe/src/components/block/modal/ReviewWriteModal.tsx
  fe/src/components/block/sideBar/SideBar.tsx
  fe/src/components/layout/GridTemplate.tsx
  fe/src/page/Common.tsx
  fe/src/page/PopOver.tsx
  fe/src/routes/router.tsx
  fe/src/store/useReviewStore.ts
Labels: 프런트

#351 [Fe/346] 질문자 리뷰조회(CodeComment)구현
  fe/src/components/block/Content/ReadQuestion.tsx
  fe/src/components/block/modal/ReviewShowModal.tsx
  fe/src/components/layout/GridTemplate.tsx
  fe/src/store/useReviewStore.ts
Labels: 프런트

#359 Fe/#356 question api
  fe/src/api/axios.ts
  fe/src/api/commentApi.ts
  fe/src/api/questionApi.ts
  fe/src/api/reviewApi.ts
  fe/src/components/atom/Comment/LineCommentView.tsx
  fe/src/components/atom/Comment/LineCommentWrite.tsx
  fe/src/components/atom/card/DefaultCard.tsx
  fe/src/components/block/Content/CreateQuestion.tsx
  fe/src/components/block/Content/CreateReview.tsx
  fe/src/components/block/Content/Question.tsx
  fe/src/components/block/Content/ReadQuestion.tsx
  fe/src/components/block/Content/Request.tsx
  fe/src/components/block/Content/Review.tsx
  fe/src/components/layout/GridTemplate.tsx
  fe/src/hooks/query/question/useGetQuestions.ts
  fe/src/page/Common.tsx
  fe/src/routes/router.tsx
  fe/src/store/useReviewStore.ts
Labels: 프런트

#362 [Fe/#357] review apply
  fe/src/api/questionApi.ts
  fe/src/api/reviewApi.ts
  fe/src/components/atom/Comment/LineCommentWrite.tsx
  fe/src/components/atom/card/DefaultCard.tsx
  fe/src/components/atom/card/ReviewCard.tsx
  fe/src/components/block/Content/CreateReview.tsx
  fe/src/components/block/Content/Question.tsx
  fe/src/components/block/Content/ReadQuestion.tsx
  fe/src/components/block/Content/Review.tsx
  fe/src/components/block/modal/ReviewWriteModal.tsx
  fe/src/components/layout/GridTemplate.tsx
  fe/src/hooks/query/comment/useCreateBelowComments.ts
  fe/src/hooks/query/comment/useDeleteBelowComments.ts
  fe/src/hooks/query/comment/useGetBelowComments.ts
  fe/src/hooks/query/comment/useUpdateBelowComments.ts
  fe/src/hooks/query/review/useSaveReview.ts
Labels: 프런트

#365 [fe/#364] LineComment 세부 조정
  fe/src/components/atom/Comment/LineCommentView.tsx
  fe/src/components/block/Content/CreateReview.tsx
  fe/src/components/layout/GridTemplate.tsx
Labels: 프런트

#366 [fe/#363] helmet 및 기타 사항 처맄
  fe/package-lock.json
  fe/package.json
  fe/src/components/atom/Helmet.tsx
  fe/src/components/atom/card/DefaultCard.tsx
  fe/src/components/atom/card/ReviewList.tsx
  fe/src/components/block/Content/CreateReview.tsx
  fe/src/components/block/Content/Question.tsx
  fe/src/components/block/Content/Review.tsx
  fe/src/components/block/modal/ReviewWriteModal.tsx
  fe/src/components/block/sideBar/SideBar.tsx
  fe/src/hooks/query/question/useGetReviews.ts
  fe/src/hooks/query/question/useGetReviewsOnQuestion.ts
  fe/src/main.tsx
Labels: 프런트

#368 [Fe/#367] grid template error fix
  fe/src/components/atom/Comment/LineCommentView.tsx
  fe/src/components/atom/card/DefaultCard.tsx
  fe/src/components/block/Content/CreateReview.tsx
  fe/src/components/block/sideBar/SideBar.tsx
  fe/src/components/layout/GridTemplate.tsx
  fe/src/store/useReviewStore.ts
Labels: 프런트
